services:
  db:
    image: postgres:16-alpine
    container_name: altv_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: altv_user
      POSTGRES_PASSWORD: altv_password
      POSTGRES_DB: altv_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
