services:
  db:                                           # Name of the service

    image: postgres:14.20                       # Download official postgres version 14.20
    container_name: alt-v-db                    # The name of the container
    restart: always

    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: alt_v_db

    ports:
      - "5432:5432"
      
    volumes:
      # This maps the data to your WSL file system
      - ./postgres_data:/var/lib/postgresql/data